### ISSUE TITLE
Update tox.ini

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-project-zero#4]
We can now change `E265` in `ignore` to `E266`.

I also wouldn't mind reconsidering the `max-line-length` and (especially) `max-complexity`.

**Comment by KatherineMichel** [comment]
This is what we had in a recent release. Do you want to change to 266 now? What about others? Otherwise, I will close issue as old. @jtauber  
ignore = E265,E501
max-line-length = 100
max-complexity = 10

**Comment by KatherineMichel** [comment]
Closing issue... will reference this issue in release docs.
